openapi: 3.0.0
info:
  title: Board API
  description: hello world.
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /api/v1/boards:
    get:
      summary: 목록
      description: 게시판 목록 조회 api
      responses:
        '200':
          description: 게시판 정보 배열
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    created_at:
                      type: string
                    created_by:
                      type: string
        '400':
          description: 잘못된 파라메터
        '500':
          description: internal server error
    post:
      summary: 글작성
      description: 게시판의 새글을 작성합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                username:
                  type: string
      responses:
        '201':
            description: 정상 응답

